<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Service;

class ServiceController extends Controller
{
    
    public function createService(Request $request){
        $service = Service::create([
            'member_id' => $request->member_id,
            'cs_id' => $request->cs_id,
            'teknisi_id' => $request->teknisi_id,
            'model_iphone' => $request->model_iphone,
            'nomor_seri_imei' => $request->nomor_seri_imei,
            'versi_ios' => $request->versi_ios,
            'masuk_back_camera_05' => $request->masuk_back_camera_05,
            'masuk_back_camera_x1' => $request->masuk_back_camera_x1,
            'masuk_back_camera_x2' => $request->masuk_back_camera_x2,
            'masuk_battery_health' => $request->masuk_battery_health,
            'masuk_battery_health_notes' => $request->masuk_battery_health_notes,
            'masuk_buzzer' => $request->masuk_buzzer,
            'masuk_charging_port_ampere' => $request->masuk_charging_port_ampere,
            'masuk_charging_port_ampere_notes' => $request->masuk_charging_port_ampere_notes,
            'masuk_contras_true_tone' => $request->masuk_contras_true_tone,
            'masuk_earpiece' => $request->masuk_earpiece,
            'masuk_face_id' => $request->masuk_face_id,
            'masuk_flashlight' => $request->masuk_flashlight,
            'masuk_front_camera' => $request->masuk_front_camera,
            'masuk_gsm_4g' => $request->masuk_gsm_4g,
            'masuk_lcd_ts' => $request->masuk_lcd_ts,
            'masuk_lcd_ts_notes' => $request->masuk_lcd_ts_notes,
            'masuk_mic_record' => $request->masuk_mic_record,
            'masuk_proximity' => $request->masuk_proximity,
            'masuk_silent_mode' => $request->masuk_silent_mode,
            'masuk_taptic_engine' => $request->masuk_taptic_engine,
            'masuk_volume_up_down_on_off' => $request->masuk_volume_up_down_on_off,
            'masuk_wifi_bluetooth' => $request->masuk_wifi_bluetooth,
            'keluar_lcd_ts' => $request->keluar_lcd_ts,
            'keluar_lcd_ts_notes' => $request->keluar_lcd_ts_notes,
            'keluar_battery_health' => $request->keluar_battery_health,
            'keluar_battery_health_notes' => $request->keluar_battery_health_notes,
            'keluar_charging_port_ampere' => $request->keluar_charging_port_ampere,
            'keluar_charging_port_ampere_notes' => $request->keluar_charging_port_ampere_notes,
            'keluar_earpiece' => $request->keluar_earpiece,
            'keluar_proximity' => $request->keluar_proximity,
            'keluar_front_camera' => $request->keluar_front_camera,
            'keluar_volume_up_down_on_off' => $request->keluar_volume_up_down_on_off,
            'keluar_silent_mode' => $request->keluar_silent_mode,
            'keluar_mic_record' => $request->keluar_mic_record,
            'keluar_contras_true_tone' => $request->keluar_contras_true_tone,
            'keluar_gsm_4g' => $request->keluar_gsm_4g,
            'keluar_wifi_bluetooth' => $request->keluar_wifi_bluetooth,
            'keluar_flashlight' => $request->keluar_flashlight,
            'keluar_taptic_engine' => $request->keluar_taptic_engine,
            'keluar_buzzer' => $request->keluar_buzzer,
            'keluar_face_id' => $request->keluar_face_id,
            'keluar_touch_id' => $request->keluar_touch_id,
            'keluar_back_camera_05' => $request->keluar_back_camera_05,
            'keluar_back_camera_x1' => $request->keluar_back_camera_x1,
            'keluar_back_camera_x2' => $request->keluar_back_camera_x2,
            'keluar_unit_mati_total' => $request->keluar_unit_mati_total,
            'keluhan_masalah_device' => $request->keluhan_masalah_device,
            'kelengkapan' => $request->kelengkapan,
            'remark_sr' => $request->remark_sr,
            'remark_unit' => $request->remark_unit,
            'note_masuk' => $request->note_masuk,
            'note_keluar' => $request->note_keluar,
        ]);

        return redirect('/service')->with('OK', 'Berhasil menambahkan data service');
    }
    
    public function editService(Request $request, $id){
        $service = Service::find($id);

        $service->update([
            'status' => $request->status,
            'member_id' => $request->member_id,
            'cs_id' => $request->cs_id,
            'teknisi_id' => $request->teknisi_id,
            'model_iphone' => $request->model_iphone,
            'nomor_seri_imei' => $request->nomor_seri_imei,
            'versi_ios' => $request->versi_ios,
            'masuk_back_camera_05' => $request->masuk_back_camera_05,
            'masuk_back_camera_x1' => $request->masuk_back_camera_x1,
            'masuk_back_camera_x2' => $request->masuk_back_camera_x2,
            'masuk_battery_health' => $request->masuk_battery_health,
            'masuk_battery_health_notes' => $request->masuk_battery_health_notes,
            'masuk_buzzer' => $request->masuk_buzzer,
            'masuk_charging_port_ampere' => $request->masuk_charging_port_ampere,
            'masuk_charging_port_ampere_notes' => $request->masuk_charging_port_ampere_notes,
            'masuk_contras_true_tone' => $request->masuk_contras_true_tone,
            'masuk_earpiece' => $request->masuk_earpiece,
            'masuk_face_id' => $request->masuk_face_id,
            'masuk_flashlight' => $request->masuk_flashlight,
            'masuk_front_camera' => $request->masuk_front_camera,
            'masuk_gsm_4g' => $request->masuk_gsm_4g,
            'masuk_lcd_ts' => $request->masuk_lcd_ts,
            'masuk_lcd_ts_notes' => $request->masuk_lcd_ts_notes,
            'masuk_mic_record' => $request->masuk_mic_record,
            'masuk_proximity' => $request->masuk_proximity,
            'masuk_silent_mode' => $request->masuk_silent_mode,
            'masuk_taptic_engine' => $request->masuk_taptic_engine,
            'masuk_volume_up_down_on_off' => $request->masuk_volume_up_down_on_off,
            'masuk_wifi_bluetooth' => $request->masuk_wifi_bluetooth,
            'keluar_lcd_ts' => $request->keluar_lcd_ts,
            'keluar_lcd_ts_notes' => $request->keluar_lcd_ts_notes,
            'keluar_battery_health' => $request->keluar_battery_health,
            'keluar_battery_health_notes' => $request->keluar_battery_health_notes,
            'keluar_charging_port_ampere' => $request->keluar_charging_port_ampere,
            'keluar_charging_port_ampere_notes' => $request->keluar_charging_port_ampere_notes,
            'keluar_earpiece' => $request->keluar_earpiece,
            'keluar_proximity' => $request->keluar_proximity,
            'keluar_front_camera' => $request->keluar_front_camera,
            'keluar_volume_up_down_on_off' => $request->keluar_volume_up_down_on_off,
            'keluar_silent_mode' => $request->keluar_silent_mode,
            'keluar_mic_record' => $request->keluar_mic_record,
            'keluar_contras_true_tone' => $request->keluar_contras_true_tone,
            'keluar_gsm_4g' => $request->keluar_gsm_4g,
            'keluar_wifi_bluetooth' => $request->keluar_wifi_bluetooth,
            'keluar_flashlight' => $request->keluar_flashlight,
            'keluar_taptic_engine' => $request->keluar_taptic_engine,
            'keluar_buzzer' => $request->keluar_buzzer,
            'keluar_face_id' => $request->keluar_face_id,
            'keluar_touch_id' => $request->keluar_touch_id,
            'keluar_back_camera_05' => $request->keluar_back_camera_05,
            'keluar_back_camera_x1' => $request->keluar_back_camera_x1,
            'keluar_back_camera_x2' => $request->keluar_back_camera_x2,
            'keluar_unit_mati_total' => $request->keluar_unit_mati_total,
            'keluhan_masalah_device' => $request->keluhan_masalah_device,
            'kelengkapan' => $request->kelengkapan,
            'remark_sr' => $request->remark_sr,
            'remark_unit' => $request->remark_unit,
            'note_masuk' => $request->note_masuk,
            'note_keluar' => $request->note_keluar,
        ]);

        return redirect('/service')->with('OK', 'Berhasil menambahkan data service');
    }

}
